export const ASSIGNMENT_ACTIONS = {
    FETCH_ASSIGNMENTS: 'FETCH_ASSIGNMENTS',
    SET_ASSIGNMENTS: 'SET_ASSIGNMENTS',
    ADD_ASSIGNMENT: 'ADD_ASSIGNMENT',
    FETCH_CURRENT_ASSIGNMENT: 'FETCH_CURRENT_ASSIGNMENT',
    SET_CURRENT_ASSIGNMENT: 'SET_CURRENT_ASSIGNMENT',
};