export const CLASSROOM_ACTIONS = {
    FETCH_CLASSROOMS: 'FETCH_CLASSROOMS',
    SET_ALL_CLASSROOMS: 'SET_ALL_CLASSROOMS',
    SET_CURRENT_CLASSROOM: 'SET_CURRENT_CLASSROOM',
    CREATE_CLASSROOM: 'CREATE_CLASSROOM',
};