export const SCORE_ACTIONS = {
    FETCH_SCORE: 'FETCH_SCORE',
    SET_SCORE: 'SET_SCORE',
    ADD_SCORE: 'ADD_SCORE',
    EDIT_SCORE: 'EDIT_SCORE',
    DELETE_SCORE: 'DELETE_SCORE',
    FETCH_ASSIGNMENT_SCORES: 'FETCH_ASSIGNMENT_SCORES',
};