export const STANDARD_ACTIONS = {
    FETCH_STANDARD: 'FETCH_STANDARD',
    SET_STANDARDS: 'SET_STANDARDS',
    ADD_STANDARD: 'ADD_STANDARD',
    EDIT_STANDARD: 'EDIT_STANDARD',
    DELETE_STANDARD: 'DELETE_STANDARD',
    TAG_STANDARD: 'TAG_STANDARD',
    UNSET_STANDARDS: 'UNSET_STANDARDS',
};