export const STUDENT_ACTIONS = {
    FETCH_STUDENT: 'FETCH_STUDENT',
    SET_STUDENTS: 'SET_STUDENTS',
    ADD_STUDENT: 'ADD_STUDENT',
    EDIT_STUDENT: 'EDIT_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
};